/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.hosted.jsonc --include-runtime=false --strict-vars=false --env-interface=HostedBindings` (hash: 9056e8fff016890a119ba4cda5cf4826)
interface __BaseEnv_HostedBindings {
	BUCKET: R2Bucket;
	DB: D1Database;
	PUBLIC_ORIGIN: string;
	TURNSTILE_SITE_KEY: string;
	REGISTRATION_LIMIT: string;
	UPLOADS_ENABLED: string;
	SUPABASE_URL: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/hosted/index");
	}
	interface Env extends __BaseEnv_HostedBindings {}
}
interface HostedBindings extends __BaseEnv_HostedBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PUBLIC_ORIGIN" | "TURNSTILE_SITE_KEY" | "REGISTRATION_LIMIT" | "UPLOADS_ENABLED" | "SUPABASE_URL">> {}
}
