import type { HostedEnv } from './types';

/** The hosted app intentionally has no service worker or persistent browser storage. */
export function hostedHTML(env: HostedEnv): string {
  const config = JSON.stringify({ sitekey: env.TURNSTILE_SITE_KEY || '' }).replace(/</g, '\\u003c');
  return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="referrer" content="no-referrer"><meta name="robots" content="noindex,nofollow"><title>ShotSync · 随手传，随处取</title><style>
:root{color-scheme:dark;font-family:system-ui,-apple-system,sans-serif;background:#101217;color:#eceff5}*{box-sizing:border-box}body{margin:0}main{max-width:1040px;margin:auto;padding:28px 20px 80px}header{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:36px}.brand{font-size:24px;font-weight:750;letter-spacing:-1px}.brand span{color:#93b6ff}h1{font-size:clamp(28px,5vw,42px);letter-spacing:-1px;margin:0 0 12px}h2{font-size:19px;margin:0 0 18px}p{line-height:1.7}small,.muted{color:#a2abba;font-size:13px}.card{background:#191d26;border:1px solid #303747;border-radius:16px;padding:24px;margin-bottom:20px}.auth{max-width:480px;margin:36px auto}label{display:block;font-size:14px;margin:16px 0 7px}input,textarea,button{font:inherit}input,textarea{width:100%;background:#10141d;border:1px solid #414b60;border-radius:9px;color:inherit;padding:12px}textarea{resize:vertical;min-height:110px}button,.button{cursor:pointer;border:1px solid #48566f;background:#273248;color:#edf2ff;border-radius:9px;padding:10px 15px;font-size:14px}button:hover{background:#344665}button:disabled{opacity:.5;cursor:wait}.primary{background:#9bbbff;color:#0a1938;border-color:#9bbbff;font-weight:650}.plain{background:transparent;border-color:transparent;color:#afc9ff;padding:7px}.row{display:flex;align-items:center;flex-wrap:wrap;gap:10px}.spread{justify-content:space-between}.stack{display:grid;gap:12px}.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(210px,1fr));gap:16px}progress{width:100%;height:9px;accent-color:#9bbbff}.meters{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:18px}.tile{min-width:0;background:#191d26;border:1px solid #303747;border-radius:12px;overflow:hidden}.preview{width:100%;height:170px;object-fit:contain;background:#0c1017}.tilebody{padding:14px}.filename{overflow-wrap:anywhere;margin:0 0 8px;font-size:14px}.textpreview{white-space:pre-wrap;overflow:auto;padding:14px;max-height:170px;min-height:80px;font-size:13px}.notice{padding:12px 16px;border:1px solid #56684c;background:#1b2a22;border-radius:10px;margin:16px 0;overflow-wrap:anywhere}.error{background:#311e25;border-color:#825162;color:#ffd4dc}[hidden]{display:none!important}.device{padding:12px 0;border-bottom:1px solid #303747}.token{overflow-wrap:anywhere;user-select:all;white-space:pre-wrap}.danger{color:#ffb4be}.tabs{margin:20px 0}.empty{padding:48px;text-align:center;color:#a2abba}@media(max-width:520px){main{padding:20px 14px 50px}.card{padding:18px}.grid{grid-template-columns:1fr 1fr}.preview{height:130px}.tilebody{padding:10px}}
</style></head><body><main><header><div class="brand">Shot<span>Sync</span></div><div class="row"><span id="identity" class="muted"></span><button id="logout" hidden>退出登录</button></div></header><div id="status" class="notice" role="status" aria-live="polite" hidden></div>
<section id="auth" class="auth"><h1>随手传，随处取。</h1><p class="muted">这里是公共账号服务。想把内容放在自己的 Cloudflare？<a href="https://github.com/Defiabell/shotsync/blob/main/README.zh-CN.md#自己部署约-5-分钟">自己部署，无需注册账号</a>。</p><p class="muted">让截图和文字，在手机与电脑之间轻松流动。免费试用限 100 个账号，内容保留 7 天。</p><div id="auth-card" class="card"><div class="row tabs"><button id="tab-login" class="primary">登录</button><button id="tab-register">注册</button></div><h2 id="auth-title">欢迎回来</h2><form id="auth-form"><p class="muted">邮箱仅作为登录名，不验证邮箱，也不会发送找回密码邮件。请保存注册后显示的恢复码。</p><label for="email">邮箱</label><input id="email" type="email" autocomplete="email" maxlength="254" required><div id="recovery-wrap" hidden><label for="recovery-code">恢复码</label><input id="recovery-code" type="text" autocomplete="off" maxlength="128" spellcheck="false"></div><div id="password-wrap"><label for="password" id="password-label">密码</label><input id="password" type="password" autocomplete="current-password" minlength="10" maxlength="128" required><small>10–128 个字符</small></div><div id="captcha" hidden style="margin-top:16px"></div><button class="primary" id="auth-submit" style="width:100%;margin-top:20px">登录</button></form><div class="row" style="margin-top:16px"><button id="forgot" class="plain">用恢复码重置密码</button></div></div><div id="recovery-result" class="card" hidden><h2>请保存你的恢复码</h2><p>此恢复码仅显示一次，用于重置密码。请存到密码管理器等安全位置，不要交给他人。</p><p class="muted">如果密码和恢复码都丢失，将无法自行找回账号。重置密码后，旧恢复码立即失效。</p><code id="recovery-value" class="token"></code><div class="row" style="margin-top:16px"><button id="copy-recovery">复制恢复码</button></div><label><input id="recovery-saved" type="checkbox" style="width:auto"> 我已安全保存恢复码</label><button id="finish-recovery" class="primary" disabled>继续登录</button></div></section>
<section id="app" hidden><div class="row spread"><div><h1>你的临时中转站</h1><p class="muted">仅你的账号可访问。内容 7 天后自动过期，请及时保存。</p></div><button id="refresh">刷新</button></div><div class="card"><h2>当前额度</h2><div id="meters" class="meters"></div><p class="muted">每日额度按 UTC 零点重置；删除内容释放存储，不返还当天上传额度。图片最多 10 MiB，文字最多 100 KiB；每分钟最多上传 10 次。服务繁忙时请稍后重试。</p></div><div class="card"><h2>添加内容</h2><form id="upload-form"><label for="file">图片 · 单张最多 10 MiB</label><input id="file" type="file" accept="image/jpeg,image/png,image/webp" required><button class="primary" style="margin-top:12px">上传图片</button></form><form id="text-form"><label for="text">或者粘贴文字 · 最多 100 KiB</label><textarea id="text" placeholder="另一台设备上需要的链接、笔记……" required></textarea><button style="margin-top:12px">发送文字</button></form></div><div class="row spread" style="margin:24px 0 16px"><h2 style="margin:0">最近内容</h2><span class="muted">分享链接请只交给信任的人</span></div><div id="gallery" class="grid"></div><div id="empty" class="empty" hidden>还没有内容。传一张图片，然后在另一台设备登录试试。</div><div class="card" style="margin-top:32px"><h2>设备令牌</h2><p class="muted">供 Mac 客户端和快捷指令使用。令牌等同于访问凭证，只会显示一次；设备丢失或不再使用时，请撤销对应令牌。</p><form id="device-form" class="row"><input id="device-name" maxlength="60" required placeholder="设备名称，例如：我的 Mac" aria-label="设备名称" style="flex:1;min-width:150px"><button>生成令牌</button></form><div id="new-token" class="notice" hidden><p>请立即复制并安全保存，此令牌不会再次展示。</p><code id="token-value" class="token"></code><div class="row" style="margin-top:12px"><button id="copy-token">复制令牌</button><button id="dismiss-token">我已保存，隐藏</button></div></div><div id="devices"></div></div></section>
</main><script>
'use strict';
const config=${config};
const $=id=>document.getElementById(id);
let mode='login',user=null,captchaId=null,captchaToken='',generation=0,recoveryPending=false;
const blobs=new Set();
const errors={'Invalid email or recovery code':'邮箱或恢复码不正确。','Recovery code already used':'恢复码已使用，请使用最新保存的恢复码。','Account registration and recovery are temporarily unavailable':'注册和账号恢复暂时不可用，请稍后重试。','Account already exists. Sign in or use your recovery code.':'账号已存在，请登录或使用恢复码重置密码。','Account already exists or trial is full.':'账号已存在或试用名额已满。','Trial is full. Please try again later.':'试用名额已满，请稍后再来。','Try again later':'操作太频繁，请稍后重试。','Invalid recovery code':'邮箱或恢复码不正确。','Maximum 10 active devices':'最多添加 10 台设备，请先撤销不再使用的令牌。',unauthorized:'登录已过期，请重新登录。',beta_full:'试用名额已满，请稍后再来。',quota_exceeded:'额度已用完，请删除旧内容或等待每日额度重置。',rate_limited:'操作太频繁，请稍后重试。',invalid_credentials:'邮箱或密码不正确。',invalid_recovery_code:'邮箱或恢复码不正确。'};
function notice(message,error=false){$('status').textContent=message;$('status').classList.toggle('error',error);$('status').hidden=!message;}
function clearPrivate(){generation++;user=null;recoveryPending=false;$('recovery-value').textContent='';$('recovery-code').value='';$('recovery-result').hidden=true;$('auth-card').hidden=false;for(const url of blobs)URL.revokeObjectURL(url);blobs.clear();for(const id of ['gallery','devices','meters'])$(id).replaceChildren();$('token-value').textContent='';$('new-token').hidden=true;$('identity').textContent='';$('text').value='';$('file').value='';$('device-name').value='';$('app').hidden=true;$('auth').hidden=false;$('logout').hidden=true;}
async function api(path,options={}){const response=await fetch(path,{credentials:'same-origin',cache:'no-store',...options});if(response.status===401){clearPrivate();setMode('login');throw new Error(path==='/api/account/login'?'邮箱或密码不正确。':'登录已过期，请重新登录。');}if(!response.ok){let body={};try{body=await response.json();}catch{}const retry=response.headers.get('retry-after');throw new Error((errors[body.error]||body.error||('请求失败（'+response.status+'）'))+(retry?'；请在 '+retry+' 秒后重试':''));}if(options.blob)return response.blob();return response.status===204?{}:response.json();}
const post=(path,data)=>api(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});
async function run(button,action){button.disabled=true;try{await action();}catch(error){notice(error.message,true);}finally{button.disabled=false;}}
function setMode(next){if(recoveryPending)return;mode=next;notice('');$('auth-title').textContent={login:'欢迎回来',register:'创建你的账号',reset:'用恢复码重置密码'}[mode];$('auth-submit').textContent={login:'登录',register:'注册并获取恢复码',reset:'重置密码并获取新恢复码'}[mode];$('password').value='';$('password').autocomplete=mode==='login'?'current-password':'new-password';$('password-label').textContent=mode==='reset'?'新密码':'密码';$('recovery-wrap').hidden=mode!=='reset';$('recovery-code').required=mode==='reset';$('recovery-code').value='';$('captcha').hidden=mode==='login';$('tab-login').classList.toggle('primary',mode==='login');$('tab-register').classList.toggle('primary',mode==='register');if(mode!=='login')mountCaptcha();}
function mountCaptcha(){if(!config.sitekey||!['register','reset'].includes(mode))return;if(window.turnstile&&captchaId===null)captchaId=window.turnstile.render('#captcha',{sitekey:config.sitekey,callback:token=>captchaToken=token,'expired-callback':()=>captchaToken='','error-callback':()=>{captchaToken='';notice('验证服务暂时不可用，请稍后重试。',true);}});}
function showRecovery(code){generation++;recoveryPending=true;$('password').value='';$('recovery-code').value='';$('recovery-value').textContent=code;$('auth-card').hidden=true;$('recovery-result').hidden=false;$('recovery-saved').checked=false;$('finish-recovery').disabled=true;notice('操作成功，请先安全保存恢复码。');}
window.addEventListener('beforeunload',event=>{if(recoveryPending){event.preventDefault();event.returnValue='';}});
$('copy-recovery').onclick=()=>run($('copy-recovery'),async()=>{await navigator.clipboard.writeText($('recovery-value').textContent);notice('恢复码已复制，请存到安全位置后再继续。');});
$('recovery-saved').onchange=()=>{$('finish-recovery').disabled=!$('recovery-saved').checked;};
$('finish-recovery').onclick=()=>{if(!$('recovery-saved').checked)return;recoveryPending=false;$('recovery-value').textContent='';$('recovery-result').hidden=true;$('auth-card').hidden=false;setMode('login');notice('请使用你的密码登录。');};
if(config.sitekey){const script=document.createElement('script');script.src='https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit';script.async=true;script.onload=mountCaptcha;document.head.append(script);}
$('tab-login').onclick=()=>setMode('login');$('tab-register').onclick=()=>setMode('register');$('forgot').onclick=()=>setMode('reset');
$('auth-form').onsubmit=event=>{event.preventDefault();run($('auth-submit'),async()=>{const submittedMode=mode;const needsCaptcha=['register','reset'].includes(submittedMode);const email=$('email').value.trim(),password=$('password').value,recoveryCode=$('recovery-code').value.trim();const endpoint={login:'login',register:'register',reset:'reset-password'}[submittedMode];if(needsCaptcha&&config.sitekey&&!captchaToken)throw new Error('请完成安全验证。');try{const result=await post('/api/account/'+endpoint,{email,password,recoveryCode,turnstileToken:captchaToken});$('password').value='';if(submittedMode==='login'){await loadAccount();return;}$('email').value=email;showRecovery(result.recoveryCode);}finally{if(needsCaptcha){captchaToken='';if(captchaId!==null&&window.turnstile)window.turnstile.reset(captchaId);}}});};
$('logout').onclick=()=>run($('logout'),async()=>{try{await post('/api/account/logout',{});}finally{clearPrivate();setMode('login');}});
function bytes(value){return value>=1048576?(value/1048576).toFixed(1)+' MiB':(value/1024).toFixed(1)+' KiB';}
function meter(label,value,max,format=String){const box=document.createElement('div'),caption=document.createElement('div'),bar=document.createElement('progress');caption.className='muted';caption.textContent=label+'：'+format(value)+' / '+format(max);bar.max=max;bar.value=value;box.append(caption,bar);return box;}
function showUsage(usage,limits={}){$('meters').replaceChildren(meter('已存内容',usage.storedItems||0,limits.storedItems||100),meter('存储空间',usage.storedBytes||0,limits.storedBytes||209715200,bytes),meter('今日上传',usage.dailyUploads||0,limits.dailyUploads||50),meter('今日流量',usage.dailyBytes||0,limits.dailyBytes||104857600,bytes));}
function button(label,action){const node=document.createElement('button');node.textContent=label;node.onclick=()=>run(node,action);return node;}
async function refresh(){const stamp=generation;const data=await api('/api/list');if(stamp!==generation||!user)return;for(const url of blobs)URL.revokeObjectURL(url);blobs.clear();$('gallery').replaceChildren();showUsage(data.usage||{},data.limits||{});$('empty').hidden=data.items.length!==0;for(const item of data.items){const tile=document.createElement('article');tile.className='tile';const body=document.createElement('div');body.className='tilebody';const name=document.createElement('p');name.className='filename';name.textContent=item.name||(item.type==='text'?'文字':'图片');const expiry=document.createElement('p');expiry.className='muted';expiry.textContent=bytes(item.size)+' · '+new Date(item.expiresAt).toLocaleString('zh-CN')+' 到期';const actions=document.createElement('div');actions.className='row';actions.append(button('预览',async()=>{const stamp=generation;const blob=await api('/i/'+encodeURIComponent(item.id),{blob:true});if(stamp!==generation)return;const old=tile.querySelector('.preview,.textpreview');if(old)old.remove();if(item.type==='text'){const preview=document.createElement('div');preview.className='textpreview';preview.textContent=await blob.text();if(stamp!==generation)return;tile.prepend(preview);}else{const preview=document.createElement('img');preview.className='preview';preview.alt=item.name||'图片预览';const url=URL.createObjectURL(blob);blobs.add(url);preview.src=url;tile.prepend(preview);}}),button('取回',async()=>{const stamp=generation;const blob=await api('/i/'+encodeURIComponent(item.id),{blob:true});if(stamp!==generation)return;const url=URL.createObjectURL(blob);blobs.add(url);const anchor=document.createElement('a');anchor.href=url;anchor.download=item.name||(item.type==='text'?'text.txt':'image');anchor.click();}),button('删除',async()=>{if(!confirm('删除这条内容？此操作无法撤销。'))return;await api('/api/img/'+encodeURIComponent(item.id),{method:'DELETE'});await refresh();}));actions.append(button('分享',async()=>{const stamp=generation;const result=await post('/api/share/'+encodeURIComponent(item.id),{});if(stamp!==generation)return;const link=document.createElement('input');link.readOnly=true;link.value=result.url;link.setAttribute('aria-label','分享链接');const hint=document.createElement('p');hint.className='muted';hint.textContent='任何持有链接的人都可访问，最多 50 次；'+new Date(result.expiresAt).toLocaleString('zh-CN')+' 到期，也可提前撤销。';body.append(hint,link,button('复制链接',async()=>{await navigator.clipboard.writeText(result.url);notice('分享链接已复制。');}),button('撤销分享',async()=>{await api('/api/share/'+encodeURIComponent(item.id),{method:'DELETE'});link.remove();hint.textContent='分享已撤销。';}));}));body.append(name,expiry,actions);tile.append(body);$('gallery').append(tile);}}
async function loadDevices(){const stamp=generation;const data=await api('/api/account/devices');if(stamp!==generation||!user)return;$('devices').replaceChildren();for(const device of data.devices){const row=document.createElement('div');row.className='device row spread';const name=document.createElement('span');name.textContent=device.name;row.append(name,button('撤销',async()=>{await api('/api/account/devices/'+encodeURIComponent(device.id),{method:'DELETE'});await loadDevices();}));$('devices').append(row);}}
async function loadAccount(){const stamp=generation;const data=await api('/api/account/me');if(stamp!==generation)return;if(!data.user){clearPrivate();return;}generation++;user=data.user;$('auth').hidden=true;$('app').hidden=false;$('logout').hidden=false;$('identity').textContent=user.email;await refresh();await loadDevices();}
$('refresh').onclick=()=>run($('refresh'),refresh);
$('upload-form').onsubmit=event=>{event.preventDefault();run(event.submitter,async()=>{const file=$('file').files[0];if(!file)return;if(file.size>10485760)throw new Error('单张图片不能超过 10 MiB。');const body=new FormData();body.append('full',file);await api('/api/upload',{method:'POST',body});$('file').value='';notice('上传成功，在另一台设备登录即可取回。');await refresh();});};
$('text-form').onsubmit=event=>{event.preventDefault();run(event.submitter,async()=>{const value=$('text').value;if(new TextEncoder().encode(value).length>102400)throw new Error('文字不能超过 100 KiB。');const body=new FormData();body.append('full',new Blob([value],{type:'text/plain'}),'text.txt');await api('/api/upload',{method:'POST',body});$('text').value='';notice('文字已发送。');await refresh();});};
$('device-form').onsubmit=event=>{event.preventDefault();run(event.submitter,async()=>{const stamp=generation;const result=await post('/api/account/devices',{name:$('device-name').value.trim()});if(stamp!==generation)return;$('token-value').textContent=result.token;$('new-token').hidden=false;$('device-name').value='';await loadDevices();});};$('copy-token').onclick=()=>run($('copy-token'),async()=>{await navigator.clipboard.writeText($('token-value').textContent);notice('令牌已复制，请安全保存。');});$('dismiss-token').onclick=()=>{$('token-value').textContent='';$('new-token').hidden=true;};
loadAccount().catch(error=>notice(error.message,true));
</script></body></html>`;
}
